### ISSUE TITLE
[Bug] Hidet numpy version conflicts with Google colab version

### ISSUE THREAD

**Issue by alexeigor** [hidet-org/hidet#201]
**Describe the bug**
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow 2.12.0 requires numpy<1.24,>=1.22, but you have numpy 1.24.3 which is incompatible.
numba 0.56.4 requires numpy<1.24,>=1.18, but you have numpy 1.24.3 which is incompatible.

**To Reproduce**
https://colab.research.google.com/drive/1K0gF1lBuEx0s3i8Pm3JMw5_Njs4mgxeZ#scrollTo=oK2NFZu0BZXJ

**Enviroment**
 - Google Colab
 - T4 Gpu

**Comment by yaoyaoding** [comment]
Hi @alexeigor,

Hidet depends on numpy 1.23 (see the [setup.py](https://github.com/hidet-org/hidet/blob/main/setup.py#L26)) because we reply on the DLPack tensor exchange protocol to exchange tensors with numpy. Could you try install numpy 1.23 on your machine, which is seems supported by tensorflow/numba and hidet according to the conflict information.

**Comment by alexeigor** [comment]
@yaoyaoding thanks!
