### ISSUE TITLE
[RFC][Discussion] Tile-based Hidet Script Frontend

### ISSUE THREAD

**Issue by Aalanli** [hidet-org/hidet#330]
The present kernel-level interface, hidet script, is similar to CUDA and consequently creates issues in code reuse, maintainability and brittleness. I feel that we need to adopt tile based approaches to kernel programming similar to trition, in order to speed up development, eliminate redundant code, and aid other optimizations.

I think that we need to establish the scope of the implementation, in particular the degree of developer vs compiler effort. There are two which I think could be valuable.

1. Adopt triton semantics in single threaded execution on the block level. Eg, blocks are explicitly parallel, but within each block, we only use operators with single threaded semantics, operating on tiles. For example: Load, Store, elementwise, dot, reduce, scan. The developer specifies the concrete layout of each tile and its memory type (global, shared, registers), while the compiler takes care of inserting barriers, shared memory allocation, and distributing work in the threadblock. Some advantages of this is better code readability, the ability to create libraries, and potential vectorized prologue fusion.
2. We can erase the user specified layouts to arrive at triton, where the compiler determines the layouts of tiles through heuristics. 

In terms of vectorized prologue fusion, if we can determine the alignment of the prologue operator, then we can determine the minimal vectorizable load, I believe this algorithm is very similar to the algorithm that triton uses to figure out the layouts of intermediate tiles, but I could be over-simplifying the problem. Of course, there should be a cost model to determine whether to vectorize load, or to not fuse, or to use something like cp_async.

I am thinking that an implementation would roughly require its own set of IR, which would be lowered into C++ or hidet script.

Finally, I think we could also consider whether this is necessary at all; do we want to make a triton clone, something unique? Or it would be a better use of our time to target triton ir instead? I think the challenge would be to find a good balance between user and compiler effort, or the balance between imperative knowledge and declarative knowledge. I believe triton achieves a good balance, however, its programming model is not flexible enough to express something like FFT. In the end, the problems that tile-based approaches seek to address (imo) is tangential to the problem of heuristically determining which strategy to take (layout A vs layout B, tile sizes, etc.), and excessive code duplication in kernel programs. Is another method possible, instead of tile based approaches?

**Comment by Aalanli** [comment]
Additionally, here are my bare-bones notes on triton: https://github.com/Aalanli/rust-gpu-dsl/blob/main/Triton%20Notes.md

**Comment by yaoyaoding** [comment]
Hi @Aalanli, thanks for kicking off the discussion of hidet community's efforts on supporting triton-like block (or tile) based programming model. I would like to share what is in my mind to support similar dialect in hidet:

Because this is our first RFC, let's follow TVM's [RFC template](https://github.com/apache/tvm-rfcs/blob/main/0000-template.md) and graduately find a way for hidet to introducing new major features. 

## Part 1
In the **guide-level explanation**, we should cover:
1. A simple introduction to the programming model and its corresponding CUDA counterparts. 
   * Tile-based programming: use tile and scalar as basic arthimatic data types. 
   * Corase-grained operations: describe what a thread block should do instead of what each thread should do. 
   * Serial execution: the execution of each operation can be thought as serial execution.
2. The programming interface exposed to the kernel developers (reuse triton's design):
```python
import hidet
from hidet.dtypes import float32
from hidet.lang import attrs, spatial

# use a submodule in `hidet.script` like `block` or `tile` or anything similar
# to store the specialized operations for the dialect.
from hidet.lang import tile as T 

BLOCK_M = 64
BLOCK_N = 64
BLOCK_K = 16

# similar to other hidet script functions, we use `hidet.script` to decorate the functions written 
# in block dialect
@hidet.script    
def matmul(
    m_size: int, n_size: int, k_size: int,    # the size of matmul: a[M, K] x b[K, N] = c[M, N]
    ptr_a: ~float32, ptr_b: ~float32, ptr_c: ~float32    # ~float32: "a pointer to float32 data"
):  
    # `cuda_tile` indicate this is a function writting in block dialect (alternative: 'cuda_block')
    attrs.func_kind = 'cuda_tile'    
    
    pid = T.program_id()    # get the program id (i.e., the block index in the context of cuda programming)

    bcnt_m = (m_size + BLOCK_M - 1) / BLOCK_M
    bcnt_n = (n_size + BLOCK_N - 1) / BLOCK_N

    offset_m, offset_n = spatial(bcnt_m, bcnt_n).map(pid)  # we can also use task mapping in the dialect
    
    # We can use T.arange(...) to create a tile and support the arthimatic computation between tile
    # and scalar with the broadcasting sematics as in numpy
    range_m = offset_m * BLOCK_M + T.arange(BLOCK_M)  
    range_n = offset_n * BLOCK_N + T.arange(BLOCK_N)
    range_k = T.arange(BLOCK_K)

    # get the offset of the a/b tile
    ptrs_a = ptr_a + range_m[:, None] * k_size + range_k[None, :]  # [BLOCK_M, BLOCK_K]
    ptrs_b = ptr_b + range_k[:, None] * n_size + range_n[None, :]  # [BLOCK_K, BLOCK_N]

    # define a accumulator
    acc = T.zeros([BLOCK_M, BLOCK_N], dtype=float32)
    
    # main k-loop
    for k in range(k_size / BLOCK_K):
        # load tile a and b
        a = T.load(ptrs_a)
        b = T.load(ptrs_b)
        # matrix multiply accumulate
        c += T.dot(a, b)
        # iterate to the next tile 
        ptrs_a += BLOCK_K
        ptrs_b += BLOCK_K * n_size
    
    # write back
    ptrs_c = ptr_c + range_m[:, None] * n_size + range_n[None, :]  # [BLOCK_M, BLOCK_N]
    T.store(ptrs_c, acc)
```

3. A short introduction to the operations supported (ld/st, dot, reduce, tile creation funcs, ...).

## Part 2
In the **reference-level explanation**, we should include a more comprehensive introduction to the new dialect. We need to formally define: 1) the type system of the dialect (scalar, tile) 2) the arithmatic operations (scalar op scalar, scalar op tile, the broadcast semantics)  3) the primitive operations: load and store, dot, reduce, ... 4) the IR design for the new dialect. What new IR do we need? How to integrate the IR in our current IR? What passes do we need to a) achieve the necessary optimizations and b) lower this dialect IR to our existing hidet tensor program IR?

## Part 3
Implementation plan. This is not a part of the RFC, but our plan to implement the features of the RFC. Because this is a large feature, I will create a new branch for it and we put the RFC draft and implement this dialect in that branch. We keep our discussion in this issue.


Let's discuss offline about the design you mentioned in above.

**Comment by yaoyaoding** [comment]
Created the git branch `tile-dialect` for this major feature, and let's start working on the [RFC](https://github.com/yaoyaoding/hidet/blob/tile-dialect/rfcs/0002-tile-dialect.md).

**Comment by Aalanli** [comment]
Hi @yaoyaoding, I have some suggestions that I think needs further consideration.
### The user interface
The way triton passes compile time parameters is via tl.constexpr annotation, while the pointers are generic. I think following that design is alright. Where the caller decides the launch parameters and compile-time constants, while any verification logic could be placed in the kernel itself. I think that kernels should be placed in the global namespace, instead of being wrapped around hidet.script_module.

### The Type System
The tensor (tile) type is parameterised by its element type, its shape and an optional layout. Since the shape is a compile time constant, this makes the type a dependent type, and comparisons should be based on value, not reference.
The type system for this dialect is not very complex, we just need datatypes, int, float, etc, and pointer types of those datatypes, triton makes the distinction between a pointer of a tensor and a tensor of pointers, although I don't think we need the former as it offers no semantic difference in most cases.

### The Operations
#### Tensor Creation
full

#### Tensor Manipulation
reshape
concat
permute
slice
broadcast
expand_dims

#### Compute
elementwise
- unary
- binary
- where

reduce
scan
dot

cast
reinterpret

#### IO
load
store
atomics (cas, rmw)

#### Core
program_id

### Semantics
I think that all tiles should have value semantics, while everything is assumed to be mutable by default, as in C. This eliminates much of the complexities of reference semantics that we have to deal with, notably aliasing rules and barrier insertion later on. 

### Passes
We will need to write more passes ourselves, like constant propagation, cse, licm, etc, as the layout analyses depends on all expressions touched by a particular io operation, so we cannot simply rely on those happening in the c compiler.

**Comment by yaoyaoding** [comment]
Hi @Aalanli, thanks for your suggestions.

> The way triton passes compile time parameters is via tl.constexpr annotation, while the pointers are generic. I think following that design is alright. Where the caller decides the launch parameters and compile-time constants, while any verification logic could be placed in the kernel itself. I think that kernels should be placed in the global namespace, instead of being wrapped around hidet.script_module.
1. **generic pointer** Since hidet has already supported a more powerful pointer system, and we can use void pointer to implement the same semantics what triton's pointer supports. Thus, it is not necessary to restrict the pointer as generic pointer, but just reuse what we already have now. 
2. **verification** users can always use assert in the kernel to assert the invariant, we do not prevent user from doing this. 
3. **script module** I prefer to still reusing the existing hidet way to define functions. There is no obvious advantage to use triton's way that defines the function in global space. Better to avoid chaning existing behaviour without obvious benefit.
4. **hyper parameter passing** I prefer to the hidet way. Triton's passing machanism will mix the "runtime parameters/argument" with "hyper-parameter". 

> The tensor (tile) type is parameterised by its element type, its shape and an optional layout. Since the shape is a compile time constant, this makes the type a dependent type, and comparisons should be based on value, not reference.
The type system for this dialect is not very complex, we just need datatypes, int, float, etc, and pointer types of those datatypes, triton makes the distinction between a pointer of a tensor and a tensor of pointers, although I don't think we need the former as it offers no semantic difference in most cases.
1. **static shape** we will only allow the compile-time constant as the shape of a tile. Thus, the comparison will be value-based. 
2. **other types** see the current rfc draft for other data types.

**op** I am still desiging the op interface in hidet. 

> I think that all tiles should have value semantics, while everything is assumed to be mutable by default, as in C. This eliminates much of the complexities of reference semantics that we have to deal with, notably aliasing rules and barrier insertion later on.
Of course. Hidet script does not have reference semantics for now.

> We will need to write more passes ourselves
Of course, we will write the passes when we want to implement some analysis or transformation that existing passes/underlying compiler do not support. But all these better to be done in an gradual way, instead of design at the very beginning.
