### ISSUE TITLE
[Bug] Unexpected behavior when inputs and outputs overlap

### ISSUE THREAD

**Issue by soodoshll** [hidet-org/hidet#96]
If some tensors exist both in the inputs and outputs of a FlowGraph (a direct link), it will create a dummy output that overrides the variable name and prohibit reading from where the input is really stored. 

Though I don't think users will write such code intentionally, the current framework won't stop users to do so, which might be confusing in some cases. If the syntax of FlowGraph is SSA, inputs/outputs as an interface exposed to users are worth a sanity check. Furthermore, if in-place operators are supported in the future, it is possible that the input and output share the same storage.

**Comment by yaoyaoding** [comment]
Hi @soodoshll, could you provide a snippet of code to demostrate what you said? Such a reproducible example could be very useful to convey what the bug is and act as the first test to check whehter we address the bug in the future PR.

The current design is: when all given inputs are concrete (i.e., not symbolic), the operator will be executed imperatively. If any of the input is symbolic, the output would be a symbolic tensor with the trace recorded. We only allow symbolic tensor as graph inputs (as placeholder). The output of the graph can be the graph input directly.

**Comment by yaoyaoding** [comment]
BTW, thanks for reporting the bugs (in this and previous issues). Those that important to make hidet more robust. I will start working on the bugs you mentioned in the next week. You are also welcome to submit PRs for the bugs that you know how to fix.

**Comment by yaoyaoding** [comment]
Thanks @soodoshll!, The reason of this bug is that we created the outputs before hand, execute each operator and store their outputs. If the output of the graph is not an output of an operator, it will remain as the init value. 

The PR #110 has fixed this bug.
